version: "3.8"

services: 
    app:
        build: .
        environment: 
            FLASK_APP: ${FLASK_APP}
            FLASK_ENV: ${FLASK_ENV}
            PLATZI_DB_URI: mongodb+srv://${USER}:${PASSWORD}@${ATLAS_URI}

        volumes: 
            - ./:/usr/src/app

        ports:
            - 5000:5000

        restart: always
